routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index');


Route::group(
[
    'namespace'     => 'Admin', 
    'prefix'        => 'admin',
    'middleware'    => 'auth.admin'
], 
    function () {

        /**
         * Login
         */
        Route::get('', 'HomeController@index')->name('admin.home');
        Route::get('/login', 'LoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'LoginController@login')->name('admin.checklogin');
        Route::post('/logout', 'LoginController@logout')->name('admin.logout');

        Route::resource('carousels', 'CarouselsController');
        Route::resource('carousel-items', 'CarouselItemsController');
    }
);

app/Models/Carousel.php
<?php

namespace App\Models;

use App\Lib\Model\Base as Model;
use Illuminate\Support\Facades\DB;

/**
 * Class Carousel
 * 
 * @property int $id
 * @property string $title
 * @property bool $active
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * 
 * @property \Illuminate\Database\Eloquent\Collection $carousel_items
 *
 * @package App\Models
 */
class Carousel extends Model
{
	public function carousel_items()
	{
		return $this->hasMany(\App\Models\CarouselItem::class);
	}
    
    public function delete() 
    {
        try {
            DB::beginTransaction();
            
            foreach ($this->carousel_items as $item) {
                $item->delete();
            }
            
            parent::delete();
                        
            DB::commit();
        } catch (\PDOException $e) {
            DB::rollback();
            throw $e;
        }
    }
}

app/Http/Controllers/Admin/CarouselsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\CrudController;
use App\Models\Carousel;

class CarouselsController extends CrudController
{

    /**
     * Create a new controller instance.
     *
     * @param Carousel $model
     * @return void
     */
    public function __construct(Carousel $model)
    {
        parent::__construct();
        
        $this->model = $model;
    }
    
    protected function getEditFormRules($id) 
    {
        return array(
            'title' => 'required'
        );
    }
}

resources/views/admin/carousels/edit.blade.php
@extends('admin.crud.edit')

@section('editFormFields')
    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('title', $item->title, array('class' => 'form-control', 'id' => 'title')) }}

        @if ($errors->has('title'))
            <span class="help-block">
                <strong>{{ $errors->first('title') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group">                       
        <div class="checkbox">
            <label for="active">
            {{ Form::hidden('active', 0)}}
            {{ Form::checkbox('active', 1, $item->active == 1, array('id' => 'title'))}}
            Active
            </label>
        </div>
    </div>  
@endsection

resources/views/admin/carousels/index.blade.php
@extends('admin.crud.index')

@section('filterForm')

    {{ Form::open(array('route' => ['carousels.index', '#grid'], 'method' => 'GET')) }}
    <div class="form-group">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('filters[title]', Input::get('filters.title'), array('class' => 'form-control', 'id' => 'title')) }}
    </div>
    <div class="form-group">
        <label>Status:</label>
        <div class="radio">
          <label for="active--1">
            {{ Form::radio('filters[active]', -1, Input::get('filters.active') == -1 || !Input::get('filters'), array('id' => 'active--1')) }}                            
            All
          </label>
          <label for="active-1">
            {{ Form::radio('filters[active]', 1, Input::get('filters.active') == 1, array('id' => 'active-1')) }}                            
            Active
          </label>
          <label for="active-0">
            {{ Form::radio('filters[active]', 0, Input::get('filters') && Input::get('filters.active') == 0, array('id' => 'active-0')) }}                            
            Inactive
          </label>
        </div>
    </div>
    {{ Form::submit('Filter', array('class' => 'btn btn-small btn-success')) }}
    <a href="{{route(Route::currentRouteName())}}#grid" class="btn btn-small btn-success">Reset</a>

    {{ Form::close() }}
@endsection

@section('grid')

<div class="grid-buttons">
    <a href="{{route('carousels.create')}}" class="btn btn-small btn-success pull-right">Add new</a>
</div>        

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th><a href="{{get_sort_link('id')}}">ID</a></th>
            <th><a href="{{get_sort_link('title')}}">Title</a></th>
            <th><a href="{{get_sort_link('active')}}">Status</a></th>
            <th><a href="{{get_sort_link('created_at')}}">Created At</a></th>
            <th><a href="{{get_sort_link('updated_at')}}">Updated At</a></th>            
            <th>Actions</th>            
        </tr>
    </thead>
    <tbody>
    @foreach($items as $key => $value)
        <tr>            
            <td>{{ $value->id }}</td>
            <td><a href="{{route('carousels.edit', ['carousel' => $value->id])}}">{{ $value->title }}</a></td>
            <td><span class="btn {{ $value->active ? 'btn-success' : 'btn-danger' }}">{{ $value->active ? 'active' : 'inactive' }}</span></td>
            <td>{{ $value->getDatetimeColumn('created_at') }}</td>
            <td>{{ $value->getDatetimeColumn('updated_at') }}</td>
            <td>
              <a class="btn btn-warning grid-button" href="{{route('carousel-items.index', ['filters' => ['carousel_id' => $value->id]])}}#grid">View items</a>
                <a class="btn btn-success grid-button" href="{{route('carousels.edit', ['carousel' => $value->id])}}">Edit</a>
                {{ Form::open(array('route' => ['carousels.destroy', $value->id], 'class' => 'grid-button')) }}
                    {{ Form::hidden('_method', 'DELETE') }}
                    {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                {{ Form::close() }}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
@endsection