routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index');


Route::group(
[
    'namespace'     => 'Admin', 
    'prefix'        => 'admin',
    'middleware'    => 'auth.admin'
], 
    function () {

        /**
         * Login
         */
        Route::get('', 'HomeController@index')->name('admin.home');
        Route::get('/login', 'LoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'LoginController@login')->name('admin.checklogin');
        Route::post('/logout', 'LoginController@logout')->name('admin.logout');

        Route::resource('carousels', 'CarouselsController');
        Route::resource('carousel-items', 'CarouselItemsController');
    }
);

app/Models/CarouselItem.php
<?php

namespace App\Models;

use App\Lib\Model\Base as Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;


/**
 * Class CarouselItem
 * 
 * @property int $id
 * @property int $carousel_id
 * @property string $title
 * @property string $title_position
 * @property string $image_extension
 * @property int $order
 * 
 * @property \App\Models\Carousel $carousel
 *
 * @package App\Models
 */
class CarouselItem extends Model
{
    use \App\Lib\Model\Traits\Image;
    
    public function __construct(array $attributes = array()) 
    {
        parent::__construct($attributes);
        
       /**
        * @todo - put sizes & path in configuration file
        */
        $this->setImageSizes(
            array(
                'thumb' => array(
                    'width'     => 150,
                    'height'    => null
                ),
                'medium' => array(
                    'width'     => 400,
                    'height'    => null
                ),
                'big' => array(
                    'width'     => 1200,
                    'height'    => null
                )
            )
        );
        
        $this->setImagePath('images/carousel');
        
        
        $this->imageExtensionProperty = 'image_extension';
        $this->idProperty = 'id';
    }

    public function carousel()
	{
		return $this->belongsTo(\App\Models\Carousel::class);
	}
    
    public function getPositions()
    {
        return array(
            'left'      => 'Left', 
            'right'     => 'Right',
            'center'    => 'Center'
        );
    }
    
    public function save(array $options = array()) {
        
        $image = null;
        
        if ($this->image_extension instanceof UploadedFile) {
            $image = $this->image_extension;
            
            $this->image_extension = $image->getClientOriginalExtension();
        }
        
        try {
            DB::beginTransaction();
            
            parent::save($options);
            
            if ($image) {
                $this->storeImages($image);
            }
            
            DB::commit();
        } catch (\PDOException $e) {
            DB::rollback();
            throw $e;
        }
    }
    
    public function delete() 
    {
        try {
            parent::delete();
            
            $this->clearImages(true);
            
            DB::commit();
        } catch (\PDOException $e) {
            DB::rollback();
            throw $e;
        }
    }
}

app/Http/Controllers/Admin/CarouselItemsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\CrudController;
use App\Models\CarouselItem;
use App\Models\Carousel;

class CarouselItemsController extends CrudController
{
    
    protected $pageTitle = 'Carousel items';
    
    /**
     * Create a new controller instance.
     *
     * @param CarouselItem $model
     * @return void
     */
    public function __construct(CarouselItem $model)
    {
        parent::__construct();
        
        $this->model = $model;
    }    
    
    protected function getViewData()
    {
        return array(
            'carousels'         => (new Carousel())->getPairs('id', 'title'),
            'title_positions'   => $this->model->getPositions()
        );
    }
    
    protected function getEditFormRules($id) 
    {
        $rules = array(
            'title'             => 'required',
            'carousel_id'       => 'required',
            'title_position'    => 'required',
            'order'             => 'integer|min:0',
            'image_extension'   => ''
        );
        
        if (!$id) {
            $rules['image_extension'] = 'required|';
        }
        
        $rules['image_extension'] .= 'image';
        
        return $rules;
    }
}

resources/views/admin/carousel-items/edit.blade.php
@extends('admin.crud.edit')

@section('editFormFields')

    <div class="form-group{{ $errors->has('carousel_id') ? ' has-error' : '' }}">
        {{ Form::label('carousel_id', 'Carousel') }}
        {{ Form::select('carousel_id', array('' => 'Select') + $data['carousels'], $item->carousel_id, array('class' => 'form-control', 'id' => 'carousel_id')) }}
        @if ($errors->has('carousel_id'))
            <span class="help-block">
                <strong>{{ $errors->first('carousel_id') }}</strong>
            </span>
        @endif
    </div>

    
    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('title', $item->title, array('class' => 'form-control', 'id' => 'title')) }}

        @if ($errors->has('title'))
            <span class="help-block">
                <strong>{{ $errors->first('title') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group{{ $errors->has('title_position') ? ' has-error' : '' }}">
        {{ Form::label('title_position', 'Title Position') }}
        {{ Form::select('title_position', array('' => 'Select') + $data['title_positions'], $item->title_position, array('class' => 'form-control', 'id' => 'carousel_id')) }}
        @if ($errors->has('title_position'))
            <span class="help-block">
                <strong>{{ $errors->first('title_position') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group{{ $errors->has('image_extension') ? ' has-error' : '' }}">
        {{ Form::label('image_extension', 'Image') }}
        {{ Form::file('image_extension') }}
        @if ($errors->has('image_extension'))
            <span class="help-block">
                <strong>{{ $errors->first('image_extension') }}</strong>
            </span>
        @endif
        
        @if ($item->getImageSrc('medium'))
        <img src="{{ $item->getImageSrc('medium') }}" alt="{{ $item->title }}"/>
        @endif
    </div>

    <div class="form-group{{ $errors->has('order') ? ' has-error' : '' }}">
        {{ Form::label('order', 'Order') }}
        {{ Form::number('order', $item->order, array('class' => 'form-control form-control-number', 'id' => 'order', 'min' => 0)) }}
        @if ($errors->has('order'))
            <span class="help-block">
                <strong>{{ $errors->first('order') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group">                       
        <div class="checkbox">
            <label for="active">
            {{ Form::hidden('active', 0)}}
            {{ Form::checkbox('active', 1, $item->active == 1, array('id' => 'title'))}}
            Active
            </label>
        </div>
    </div>  
@endsection

resources/views/admin/carousel-items/index.blade.php
@extends('admin.crud.index')

@section('pageTitle')
    Carousel items
@endsection

@section('filterForm')

    {{ Form::open(array('route' => ['carousel-items.index', '#grid'], 'method' => 'GET')) }}
    <div class="form-group">
        {{ Form::label('carousel_id', 'Carousel') }}
        {{ Form::select('filters[carousel_id]', array('' => 'Select') + $data['carousels'], Input::get('filters.carousel_id'), array('class' => 'form-control', 'id' => 'carousel_id')) }}
    </div>
    <div class="form-group">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('filters[title]', Input::get('filters.title'), array('class' => 'form-control', 'id' => 'title')) }}
    </div>
    <div class="form-group">
        {{ Form::label('title_position', 'Title Position') }}
        {{ Form::select('filters[title_position]', array('' => 'Select') + $data['title_positions'], Input::get('filters.title_position'), array('class' => 'form-control', 'id' => 'carousel_id')) }}
    </div>
    <div class="form-group">
        <label>Status:</label>
        <div class="radio">
          <label for="active--1">
            {{ Form::radio('filters[active]', -1, Input::get('filters.active') == -1 || !Input::get('filters'), array('id' => 'active--1')) }}                            
            All
          </label>
          <label for="active-1">
            {{ Form::radio('filters[active]', 1, Input::get('filters.active') == 1, array('id' => 'active-1')) }}                            
            Active
          </label>
          <label for="active-0">
            {{ Form::radio('filters[active]', 0, Input::get('filters') && Input::get('filters.active') == 0, array('id' => 'active-0')) }}                            
            Inactive
          </label>
        </div>
    </div>
    {{ Form::submit('Filter', array('class' => 'btn btn-small btn-success')) }}
    <a href="{{route(Route::currentRouteName())}}#grid" class="btn btn-small btn-success">Reset</a>

    {{ Form::close() }}
@endsection

@section('grid')

<div class="grid-buttons">
    <a href="{{route('carousel-items.create')}}" class="btn btn-small btn-success pull-right">Add new</a>
</div>        

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th><a href="{{get_sort_link('id')}}">ID</a></th>               
            <th><a href="{{get_sort_link('carousel')}}">Carousel</a></th>
            <th><a href="{{get_sort_link('title')}}">Image</a></th>
            <th><a href="{{get_sort_link('title_position')}}">Title Position</a></th>
            <th><a href="{{get_sort_link('order')}}">Order</a></th>
            <th><a href="{{get_sort_link('active')}}">Status</a></th>
            <th><a href="{{get_sort_link('created_at')}}">Created At</a></th>
            <th><a href="{{get_sort_link('updated_at')}}">Updated At</a></th>            
            <th>Actions</th>            
        </tr>
    </thead>
    <tbody>
    @foreach($items as $key => $value)
        <tr>            
            <td>{{ $value->id }}</td>
            <td><a href="{{route('carousels.edit', ['id' => $value->carousel->id])}}">{{ $value->carousel->title }}</a></td>
            <td><a href="{{route('carousel-items.edit', ['carousel' => $value->id])}}">{{ $value->title }}<br/><img src="{{ $value->getImageSrc('thumb') }}" alt="{{ $value->title }}"/></a></td>
            <td>{{ $value->title_position }}</td>
            <td>{{ $value->order }}</td>
            <td><span class="btn {{ $value->active ? 'btn-success' : 'btn-danger' }}">{{ $value->active ? 'active' : 'inactive' }}</span></td>
            <td>{{ $value->getDatetimeColumn('created_at') }}</td>
            <td>{{ $value->getDatetimeColumn('updated_at') }}</td>
            <td>
                <a class="btn btn-success grid-button" href="{{route('carousel-items.edit', ['carousel' => $value->id])}}">Edit</a>
                {{ Form::open(array('route' => ['carousel-items.destroy', $value->id], 'class' => 'grid-button')) }}
                    {{ Form::hidden('_method', 'DELETE') }}
                    {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                {{ Form::close() }}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
@endsection